export const ROLES = {
  ADMIN: 'ADMIN',
  TEACHER: 'TEACHER',
  FRESH_STUDENT: 'FRESH_STUDENT',
  ADVANCED_STUDENT: 'ADVANCED_STUDENT',
}

export const TEACHER_TYPES = {
  FRESH_TEACHER: 'FRESH_TEACHER',
  ADVANCED_TEACHER: 'ADVANCED_TEACHER',
}

export const STUDENT_STATUS = {
  FRESH: 'FRESH',
  ADVANCED: 'ADVANCED',
}

export const REGISTRATION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
}

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
}

export const CLASS_CHANGE_STATUS = {
  OPEN: 'OPEN',
  MATCHED: 'MATCHED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
}

export const SCHEDULE_TYPE = {
  CLASS: 'CLASS',
  TUTORIAL: 'TUTORIAL',
}

export const DAYS_OF_WEEK = [
  'MONDAY',
  'TUESDAY',
  'WEDNESDAY',
  'THURSDAY',
  'FRIDAY',
  'SATURDAY',
  'SUNDAY',
]

export const EXAM_TYPE = {
  WRITTEN: 'WRITTEN',
  PRACTICAL: 'PRACTICAL',
}

export const NOTIFICATION_TYPE = {
  SUCCESS: 'SUCCESS',
  INFO: 'INFO',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
}

export const CLASS_TYPE = {
  FRESH: 'FRESH',
  ADVANCED: 'ADVANCED',
}
